### ISSUE TITLE
android/mips fails to open path settings

### ISSUE THREAD

**Issue by skmp** [reicast/reicast-emulator#390]
W/System.err( 1113): java.lang.ClassCastException: android.widget.TextView cannot be cast to android.widget.Button
W/System.err( 1113):    at com.reicast.emulator.config.OptionsFragment.onViewCreated(OptionsFragment.java:70)
W/System.err( 1113):    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:941)
W/System.err( 1113):    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104)
W/System.err( 1113):    at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
W/System.err( 1113):    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1467)
W/System.err( 1113):    at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:440)
W/System.err( 1113):    at android.os.Handler.handleCallback(Handler.java:725)
W/System.err( 1113):    at android.os.Handler.dispatchMessage(Handler.java:92)
W/System.err( 1113):    at android.os.Looper.loop(Looper.java:137)
W/System.err( 1113):    at android.app.ActivityThread.main(ActivityThread.java:5039)
W/System.err( 1113):    at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err( 1113):    at java.lang.reflect.Method.invoke(Method.java:511)
W/System.err( 1113):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
W/System.err( 1113):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
W/System.err( 1113):    at dalvik.system.NativeStart.main(Native Method)

**Comment by skmp** [comment]
@LoungeKatt closing this as it's hopefully fixed
