### ISSUE TITLE
reicast-joyconfig crashes in the second button map

### ISSUE THREAD

**Issue by sergiobenrocha2** [reicast/reicast-emulator#848]
It can map the button for exit, but when I try to map A, it crashes:

```
15: Sony PLAYSTATION(R)3 Controller (/dev/input/event15, usb-0000:00:14.0-3/input0)
Please enter the device id: 15
Using device 15...
Name: Sony PLAYSTATION(R)3 Controller
File: /dev/input/event15
Phys: usb-0000:00:14.0-3/input0
Do you want to map a button to exit the emulator [Y/n] 
Press the that button now...
emulator escape button mapped to 704 (BTN_TRIGGER_HAPPY).
Do you want to map the A button? [Y/n] 
Press the A button now...
Traceback (most recent call last):
  File "/usr/bin/reicast-joyconfig", line 237, in <module>
    mapping = setup_device(dev_id)
  File "/usr/bin/reicast-joyconfig", line 147, in setup_device
    print_mapped_button("%s button" % button, event)
  File "/usr/bin/reicast-joyconfig", line 89, in print_mapped_button
    code_id = evdev.ecodes.BTN[event.code]
KeyError: 302
```

Python 2.7.6, Xubuntu 14.04.

If I try with Python 3:

```
15: Sony PLAYSTATION(R)3 Controller (/dev/input/event15, usb-0000:00:14.0-3/input0)
Please enter the device id: 15
Using device 15...
Name: Sony PLAYSTATION(R)3 Controller
File: /dev/input/event15
Phys: usb-0000:00:14.0-3/input0
Do you want to map a button to exit the emulator [Y/n] 
Press the that button now...
emulator escape button mapped to 704 (BTN_TRIGGER_HAPPY).
Do you want to map the A button? [Y/n] 
Press the A button now...
Traceback (most recent call last):
  File "/usr/bin/reicast-joyconfig", line 237, in <module>
    mapping = setup_device(dev_id)
  File "/usr/bin/reicast-joyconfig", line 147, in setup_device
    print_mapped_button("%s button" % button, event)
  File "/usr/bin/reicast-joyconfig", line 89, in print_mapped_button
    code_id = evdev.ecodes.BTN[event.code]
KeyError: 302
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 138, in apport_excepthook
    os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
PermissionError: [Errno 13] Permission denied: '/var/crash/_usr_bin_reicast-joyconfig.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/reicast-joyconfig", line 237, in <module>
    mapping = setup_device(dev_id)
  File "/usr/bin/reicast-joyconfig", line 147, in setup_device
    print_mapped_button("%s button" % button, event)
  File "/usr/bin/reicast-joyconfig", line 89, in print_mapped_button
    code_id = evdev.ecodes.BTN[event.code]
KeyError: 302
```

**Comment by fluffymadness** [comment]
If you comment this line out
# print_mapped_button("%s button" % button, event)
it should work

**Comment by Holzhaus** [comment]
@sergiobenrocha2 Can you try [this version](https://github.com/reicast/reicast-emulator/blob/fix/issue-848/shell/linux/tools/reicast-joyconfig.py) of the tool and tell me if it works for you? Commit 5aed3dffc4a5e031a86e2b292aad410b8e9ae65e should fix that issue.

**Comment by sergiobenrocha2** [comment]
@Holzhaus it works, thanks
