### ISSUE TITLE
Segfault if you try to run with gdb

### ISSUE THREAD

**Issue by sergiobenrocha2** [reicast/reicast-emulator#865]
I can't debug another issue because reicast is segfauting if I try to use gdb.

```
Program received signal SIGSEGV, Segmentation fault.
bm_GetCode (addr=<optimized out>) at ../../core/hw/sh4/dyna/blockmanager.cpp:97
97      return (DynarecCodeEntryPtr)rv;
(gdb) bt full
#0  bm_GetCode (addr=<optimized out>) at ../../core/hw/sh4/dyna/blockmanager.cpp:97
No locals.
#1  0x0000000000aa7353 in ngen_mainloop (v_cntx=0x7fffd1da0000) at ../../core/rec-x64/rec_x64.cpp:50
        rcb = <optimized out>
        ctx = 0x7fffcdca0000
#2  0x000000000049f7c8 in recSh4_Run () at ../../core/hw/sh4/dyna/driver.cpp:91
        __FUNCTION__ = "recSh4_Run"
#3  0x00000000004088cd in main (argc=1, argv=0x7fffffffdf78) at ../../core/linux-dist/main.cpp:443
        dirs = std::vector of length 5, capacity 5 = {"/usr/share/xubuntu/reicast", "/usr/share/xfce4/reicast", "/usr/local/share//reicast", "/usr/share//reicast", "/usr/share/reicast"}
```

backtrace with Dynarec.Enabled = 1, you can't even see dreamcast bios boot.

**Comment by sergiobenrocha2** [comment]
With the interpreter, no game loaded:

```
Program received signal SIGSEGV, Segmentation fault.
pvr_write_area1_32 (addr=<optimized out>, data=0) at ../../core/hw/pvr/pvr_mem.cpp:216
216		*(u32*)&vram[pvr_map32(addr) & VRAM_MASK] = data;
(gdb) bt full
#0  pvr_write_area1_32 (addr=<optimized out>, data=0) at ../../core/hw/pvr/pvr_mem.cpp:216
No locals.
#1  0x000000000047c20b in Sh4_int_Run () at ../../core/hw/sh4/interpr/sh4_interpreter.cpp:56
        addr = <optimized out>
        op = <optimized out>
        l = 56
#2  0x00000000004088cd in main (argc=1, argv=0x7fffffffdf78) at ../../core/linux-dist/main.cpp:443
        dirs = std::vector of length 5, capacity 5 = {"/usr/share/xubuntu/reicast", "/usr/share/xfce4/reicast", "/usr/local/share//reicast", "/usr/share//reicast", "/usr/share/reicast"}
```

**Comment by skmp** [comment]
This is normal behavior - we use segfaults for optimizations. See #1102. Also, this kind of 'getting started' discussion could also be done in http://forum.reicast.com to avoid overloading the tracker :)
